---
- name: Web server installed
  hosts: group1
  become: yes
  tasks:
  - name: latest ngnix version installed
    apt:
      name: nginx-light
      state: latest
      update_cache: true
  - name: nginx enabled and running
    service:
      name: nginx
      enabled: true
      state: started
