---
- name: Web server installed
  hosts: group1
  become: yes

  vars:
    my_name: First Name

  tasks:
  - name: latest nginx version installed
    apt:
      name: nginx-light
      state: latest
      update_cache: true
  - name: nginx enabled and running
    service:
      name: nginx
      enabled: true
      state: started
